name: Android Native

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd ./Platforms/Android
          ./gradlew platformchannels:publishReleasePublicationToArtifactsRepository

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Maven
          path: ./artifacts/maven/