name: Android Native

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build Platforms/build.proj -t:BuildAndroid

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Maven
          path: ./Platforms/android/platformchannels/build/repo
