name: Mac / iOS Native

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:

    name: Build Apple Library
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build
        run: dotnet build Platforms/build.proj -t:BuildApple

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DotNetPlatformChannels.xcframework
          path: ./Platforms/Apple/DotNetPlatformChannels/build/DotNetPlatformChannels.xcframework